### ISSUE TITLE
Create a video like the ones on the roots site for setup and configuration

### ISSUE THREAD

**Issue by Passenger-Inspired** [carrot/roots-contentful#6]
Would really appreciate if you could provide additional detail or do a demo of how to set up this and run the plugin.

I am having so many problems with getting this to work and I have no idea where to start with regards to debugging unfortunately.

I did everything specified in the README, but still no luck unfortunately. I just get a bunch of errors thrown.

Appreciate your time and thanks for a great system and integration

**Comment by jenius** [comment]
Hey Ben,

Could you provide a little more detail on what errors you are running into? This would help a lot with debugging. I know @joshrowley has implemented this plugin and I have as well and didn't have an issue getting it working. There are pretty thorough docs in the readme...

**Comment by joshrowley** [comment]
There's also a [project template](https://github.com/carrot/sprout-static-cms) for setting this up alongside with netlify hosting. You'll need to install [sprout](https://github.com/carrot/sprout) to get that set up. If you need further assistance, just let us know what error messages you're running into.

**Comment by Passenger-Inspired** [comment]
Is netlify a requirement when using roots? 

Apologies for not replying sooner, please find the detail on the problem below:

I am using the default template for roots and applied the configuration specified in your docs to my app.coffee, as well as used the template which you have created '_post.jade' as a quick test.

**The Errors in the CLI from running 'roots watch'**

    to: wrong arguments

    toEnd: wrong arguments

    compiling...


    ------------ ERROR ------------

    TypeError: /Users/me/Documents/dev/TestProject/views/_post.jade:2
        1| ul
      > 2|     - for post in contentful.posts
        3|       li
        4|         h2= post.title
        5|         p= markdown(post.body)

    Cannot read property 'posts' of undefined
        at eval (eval at <anonymous>   (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:13:25)
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:69:4)
        at /usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:153:35
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:197:10)
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:179:21)
        at Transformer.exports.jade.Transformer.async [as _renderAsync] (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/transformers.js:295:19)
        at /usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:110:12
        at new Promise (/usr/local/lib/node_modules/roots/node_modules/transformers/node_modules/promise/index.js:42:5)
        at Transformer.render (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:107:10)
        at Object.exports.compile (/usr/local/lib/node_modules/roots/lib/adapters/jade.js:24:17)
        at Compiler.compile_single (/usr/local/lib/node_modules/roots/lib/compiler.js:167:19)
        at Promise.FulfilledPromise._when (/usr/local/lib/node_modules/roots/node_modules/when/when.js:447:48)
        at Array.deliver [as 0] (/usr/local/lib/node_modules/roots/node_modules/when/when.js:108:7)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at Array.1784 (/usr/local/lib/node_modules/roots/node_modules/when/when.js:130:5)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at drainQueue (/usr/local/lib/node_modules/roots/node_modules/when/when.js:819:3)
        at process._tickCallback (node.js:419:13)

    done!
    server started on port 1111



    ------------ ERROR ------------

    TypeError: /Users/me/Documents/dev/TestProject/views/index.jade:1
      > 1| != title_with_markup()
        2|
        3| :markdown
        4|   **Whoo!** You got everything working. Now get to making cool things : )

    undefined is not a function
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:8:33)
        at /usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:153:35
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:197:10)
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:179:21)
        at Transformer.exports.jade.Transformer.async [as _renderAsync] (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/transformers.js:295:19)
        at /usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:110:12
        at new Promise (/usr/local/lib/node_modules/roots/node_modules/transformers/node_modules/promise/index.js:42:5)
        at Transformer.render (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:107:10)
        at Object.exports.compile (/usr/local/lib/node_modules/roots/lib/adapters/jade.js:24:17)
        at Compiler.compile_single (/usr/local/lib/node_modules/roots/lib/compiler.js:167:19)
        at Promise.FulfilledPromise._when (/usr/local/lib/node_modules/roots/node_modules/when/when.js:447:48)
        at Array.deliver [as 0] (/usr/local/lib/node_modules/roots/node_modules/when/when.js:108:7)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at Array.1786 (/usr/local/lib/node_modules/roots/node_modules/when/when.js:130:5)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at drainQueue (/usr/local/lib/node_modules/roots/node_modules/when/when.js:819:3)
        at process._tickCallback (node.js:419:13)




    ------------ ERROR ------------

    TypeError: /Users/me/Documents/dev/TestProject/node_modules/roots-contentful/test/fixtures/basic/index.jade:2
        1| ul
      > 2|   - for p in contentful.blog_posts
        3|     li
        4|       h1= p.title
        5|       p= p.body

    Cannot read property 'blog_posts' of undefined
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:13:25)
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:69:4)
        at /usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:153:35
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:197:10)
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:179:21)
        at Transformer.exports.jade.Transformer.async [as _renderAsync] (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/transformers.js:295:19)
        at /usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:110:12
        at new Promise (/usr/local/lib/node_modules/roots/node_modules/transformers/node_modules/promise/index.js:42:5)
        at Transformer.render (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:107:10)
        at Object.exports.compile (/usr/local/lib/node_modules/roots/lib/adapters/jade.js:24:17)
        at Compiler.compile_single (/usr/local/lib/node_modules/roots/lib/compiler.js:167:19)
        at Promise.FulfilledPromise._when (/usr/local/lib/node_modules/roots/node_modules/when/when.js:447:48)
        at Array.deliver [as 0] (/usr/local/lib/node_modules/roots/node_modules/when/when.js:108:7)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at Array.1832 (/usr/local/lib/node_modules/roots/node_modules/when/when.js:130:5)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at drainQueue (/usr/local/lib/node_modules/roots/node_modules/when/when.js:819:3)
        at process._tickCallback (node.js:419:13)




    ------------ ERROR ------------

    TypeError: /Users/me/Documents/dev/TestProject/node_modules/roots-contentful/test/fixtures/missing_config/index.jade:2
        1| ul
      > 2|   - for p in contentful.blog_posts
        3|     li
        4|       h1= p.title
        5|       p= p.body

    Cannot read property 'blog_posts' of undefined
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:13:25)
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:69:4)
        at /usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:153:35
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:197:10)
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:179:21)
        at Transformer.exports.jade.Transformer.async [as _renderAsync] (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/transformers.js:295:19)
        at /usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:110:12
        at new Promise (/usr/local/lib/node_modules/roots/node_modules/transformers/node_modules/promise/index.js:42:5)
        at Transformer.render (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:107:10)
        at Object.exports.compile (/usr/local/lib/node_modules/roots/lib/adapters/jade.js:24:17)
        at Compiler.compile_single (/usr/local/lib/node_modules/roots/lib/compiler.js:167:19)
        at Promise.FulfilledPromise._when (/usr/local/lib/node_modules/roots/node_modules/when/when.js:447:48)
        at Array.deliver [as 0] (/usr/local/lib/node_modules/roots/node_modules/when/when.js:108:7)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at Array.1834 (/usr/local/lib/node_modules/roots/node_modules/when/when.js:130:5)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at drainQueue (/usr/local/lib/node_modules/roots/node_modules/when/when.js:819:3)
        at process._tickCallback (node.js:419:13)




    ------------ ERROR ------------

    TypeError: /Users/me/Documents/dev/TestProject/node_modules/roots-contentful/test/fixtures/custom_name/index.jade:2
        1| ul
      > 2|   - for p in contentful.press_links
        3|     li
        4|       h1= p.title
        5|       p= p.body

    Cannot read property 'press_links' of undefined
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:13:25)
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:69:4)
        at /usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:153:35
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:197:10)
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:179:21)
        at Transformer.exports.jade.Transformer.async [as _renderAsync] (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/transformers.js:295:19)
        at /usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:110:12
        at new Promise (/usr/local/lib/node_modules/roots/node_modules/transformers/node_modules/promise/index.js:42:5)
        at Transformer.render (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:107:10)
        at Object.exports.compile (/usr/local/lib/node_modules/roots/lib/adapters/jade.js:24:17)
        at Compiler.compile_single (/usr/local/lib/node_modules/roots/lib/compiler.js:167:19)
        at Promise.FulfilledPromise._when (/usr/local/lib/node_modules/roots/node_modules/when/when.js:447:48)
        at Array.deliver [as 0] (/usr/local/lib/node_modules/roots/node_modules/when/when.js:108:7)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at Array.1838 (/usr/local/lib/node_modules/roots/node_modules/when/when.js:130:5)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at drainQueue (/usr/local/lib/node_modules/roots/node_modules/when/when.js:819:3)
        at process._tickCallback (node.js:419:13)




    ------------ ERROR ------------

    TypeError: /Users/me/Documents/dev/TestProject/node_modules/roots-contentful/test/fixtures/single_entry/index.jade:1
      > 1| - for p in contentful.blog_posts
        2|   h1= p.title
        3|   p= p.body
        4|   a(href= p._url) Link

    Cannot read property 'blog_posts' of undefined
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:10:25)
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:72:4)
        at /usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:153:35
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:197:10)
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:179:21)
        at Transformer.exports.jade.Transformer.async [as _renderAsync] (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/transformers.js:295:19)
        at /usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:110:12
        at new Promise (/usr/local/lib/node_modules/roots/node_modules/transformers/node_modules/promise/index.js:42:5)
        at Transformer.render (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:107:10)
        at Object.exports.compile (/usr/local/lib/node_modules/roots/lib/adapters/jade.js:24:17)
        at Compiler.compile_single (/usr/local/lib/node_modules/roots/lib/compiler.js:167:19)
        at Promise.FulfilledPromise._when (/usr/local/lib/node_modules/roots/node_modules/when/when.js:447:48)
        at Array.deliver [as 0] (/usr/local/lib/node_modules/roots/node_modules/when/when.js:108:7)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at Array.1842 (/usr/local/lib/node_modules/roots/node_modules/when/when.js:130:5)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at drainQueue (/usr/local/lib/node_modules/roots/node_modules/when/when.js:819:3)
        at process._tickCallback (node.js:419:13)




    ------------ ERROR ------------

    TypeError: /Users/me/Documents/dev/TestProject/node_modules/roots-contentful/test/fixtures/single_entry/views/_blog_post.jade:1
      > 1| h1= entry.title
        2| p= entry.body
        3| p= wow
        4|

    Cannot read property 'title' of undefined
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:8:62)
        at /usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:153:35
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:197:10)
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:179:21)
        at Transformer.exports.jade.Transformer.async [as _renderAsync] (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/transformers.js:295:19)
        at /usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:110:12
        at new Promise (/usr/local/lib/node_modules/roots/node_modules/transformers/node_modules/promise/index.js:42:5)
        at Transformer.render (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:107:10)
        at Object.exports.compile (/usr/local/lib/node_modules/roots/lib/adapters/jade.js:24:17)
        at Compiler.compile_single (/usr/local/lib/node_modules/roots/lib/compiler.js:167:19)
        at Promise.FulfilledPromise._when (/usr/local/lib/node_modules/roots/node_modules/when/when.js:447:48)
        at Array.deliver [as 0] (/usr/local/lib/node_modules/roots/node_modules/when/when.js:108:7)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at Array.1864 (/usr/local/lib/node_modules/roots/node_modules/when/when.js:130:5)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at drainQueue (/usr/local/lib/node_modules/roots/node_modules/when/when.js:819:3)
        at process._tickCallback (node.js:419:13)




    ------------ ERROR ------------

    TypeError: /Users/me/Documents/dev/TestProject/node_modules/roots-contentful/test/fixtures/single_entry_custom/views/_blog_post.jade:1
      > 1| h1= entry.title
        2| p= entry.body
        3| p= wow
        4|

    Cannot read property 'title' of undefined
        at eval (eval at <anonymous> (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:152:8), <anonymous>:8:62)
        at /usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:153:35
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:197:10)
        at Object.exports.render (/usr/local/lib/node_modules/roots/node_modules/jade/lib/jade.js:179:21)
        at Transformer.exports.jade.Transformer.async [as _renderAsync] (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/transformers.js:295:19)
        at /usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:110:12
        at new Promise (/usr/local/lib/node_modules/roots/node_modules/transformers/node_modules/promise/index.js:42:5)
        at Transformer.render (/usr/local/lib/node_modules/roots/node_modules/transformers/lib/shared.js:107:10)
        at Object.exports.compile (/usr/local/lib/node_modules/roots/lib/adapters/jade.js:24:17)
        at Compiler.compile_single (/usr/local/lib/node_modules/roots/lib/compiler.js:167:19)
        at Promise.FulfilledPromise._when (/usr/local/lib/node_modules/roots/node_modules/when/when.js:447:48)
        at Array.deliver [as 0] (/usr/local/lib/node_modules/roots/node_modules/when/when.js:108:7)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at Array.1866 (/usr/local/lib/node_modules/roots/node_modules/when/when.js:130:5)
        at runHandlers (/usr/local/lib/node_modules/roots/node_modules/when/when.js:370:12)
        at drainQueue (/usr/local/lib/node_modules/roots/node_modules/when/when.js:819:3)
        at process._tickCallback (node.js:419:13)

**The configuration settings look as follows**

  module.exports =
    extensions: [
      contentful({
        access_token: 'myAPIKey'
        space_id: 'mySpaceId'
        content_types: [
          {
            id: 'myContentTypeId',
            name: 'posts',
            template: 'views/_post.jade',
            filters: {
              'fields.environment[in]': ['staging', 'production']
            },
            path: (e) -> "#{e.category}/#{slugify(e.title)}"
          }
        ]
      })
    ]

I am pretty sure it is nothing to do with the plugin itself, and it is a mistake from myself so I do apologise in advance, I just wondered if you guys had seen the error before or came across a similar issue.

Thanks in advance,

B

**Comment by joshrowley** [comment]
No, sorry netlify is not a requirement, I just made a template that helps you get set up with contentful and netlify, although I now think I should separate those into two templates.

What version of roots are you using? You should be able to output that info with `$ roots -v`. You need to be on roots version 3 for this extension to work, if you're on v2, you'll need to upgrade with `npm install roots@pre -g`. Version 3 is nearing a final public release, but you'll need to use the prerelease in the mean time.

**Comment by Passenger-Inspired** [comment]
Ahhh that would be great if that happened.

Yeah that is probably it, running `npm install roots@pre -g` doesn't seem to work unfortunately.

Running `roots -v` after that install returns the following `zsh: command not found: roots`

Thanks for your help this far, it is very much appreciated.

Ben

**Comment by jenius** [comment]
Try opening up a new shell window and see if roots is found. If not, there's an issue with your machine and node version, this is a node installation problem not a roots problem...

**Comment by Passenger-Inspired** [comment]
It must be a problem with my machine.

With that said, this is the output of that install command and it just doesn't seem correct

    > posix@1.0.4 install /usr/local/lib/node_modules/roots/node_modules/posix
   > node-gyp rebuild

    CXX(target) Release/obj.target/posix/src/posix.o
    SOLINK_MODULE(target) Release/posix.node
    SOLINK_MODULE(target) Release/posix.node: Finished

Could you confirm this is the correct output when you attempt to install the pre release?

Ben

**Comment by jenius** [comment]
This is the correct output. That's posix being installed, which is normal, as it's a C-linked dependency.

**Comment by Passenger-Inspired** [comment]
All sorted. Closing off, thanks for the help. It was the versioning.
