### ISSUE TITLE
Running roots compile or roots watch results in error

### ISSUE THREAD

**Issue by Passenger-Inspired** [carrot/roots-contentful#7]
Apologies for the constant pestering but I am receiving an error whenever running `roots compile` or `roots watch`

My roots version is 3.0.0-rc.10.

The error is as follows:

  `compiling... Potentially unhandled rejection [3] TypeError: Cannot call method 'renderFile' of undefined
  at /Users/me/Documents/dev/testproject/node_modules/roots-contentful/lib/index.js:197:31
  at mapWithIndex (/Users/me/Documents/dev/testproject/node_modules/roots-   contentful/node_modules/when/lib/decorators/array.js:153:12)
  at /Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/decorators/fold.js:16:19
  at tryCatchReject3 (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/makePromise.js:769:7)
  at runContinuation3 (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/makePromise.js:738:4)
  at Fulfilled.fold (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/makePromise.js:540:4)
  at /Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/decorators/fold.js:15:25
  at Pending.<anonymous> (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/makePromise.js:368:7)
  at tryCatchReject (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/makePromise.js:758:30)
  at runContinuation1 (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/makePromise.js:728:4)
  at Fulfilled.when (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/makePromise.js:544:4)
  at ContinuationTask.run (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/makePromise.js:648:24)
  at runQueue (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/Scheduler.js:75:18)
  at Scheduler._drain (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/Scheduler.js:50:3)
  at Scheduler.drain (/Users/me/Documents/dev/testproject/node_modules/roots-contentful/node_modules/when/lib/Scheduler.js:26:9)
  at process._tickCallback (node.js:442:13)`

My config settings are as follows:

    contentful = require 'roots-contentful'

    module.exports =
    extensions: [
      contentful({
        access_token: 'MYAPIKEY'
        space_id: 'MYSPACEID'
        content_types: [
          {
            id: 'MYCONTENTMODELID',
            name: 'posts',
            template: 'views/_post.jade',
            path: (e) -> "/#{e.category}/#{e.title}"
          }
        ]
      })
    ]

The template I am using for my Jade file, is a copy of the one you guys have provided in your documentation. 

Thanks in advance.

Ben

**Comment by joshrowley** [comment]
It looks like roots-contentful is not correctly finding the correct compiler from roots to generate the single page views using your template.

Can you confirm that you have `jade` listed in your `package.json` dependencies and that your template file exists at `views/_post.jade` (and in particular that you have the `.jade` extension at the end).

**Comment by jenius** [comment]
Also make sure you ran `npm install` in your project!

**Comment by Passenger-Inspired** [comment]
I updated my roots version to rc10 but, I was still using an old template.

Apologies for wasting your time, once again.

Really appreciate your quick support and generous help.

Ben

**Comment by jenius** [comment]
Glad this worked out! If you are looking to migrate an older project, feel free to [check out this guide](http://roots-web.bitballoon.com/articles/upgrading) from our WIP docs site.
